---
- name: Add plex repo
  yum_repository:
    name: plex
    description: Plex Media Server repo
    baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
    gpgcheck: true
    gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: Install Plex Media Server package
  yum:
    name: plexmediaserver
    state: latest

- name: Start and enable plex
  service:
    name: plexmediaserver
    state: started
    enabled: true

- name: Plex firewall rule
  firewalld:
    port: 32400/tcp
    permanent: true
    state: enabled
    immediate: true
