---
- name: Add plex repository
  yum_repository:
    name: plex
    description: Plex Media Server repo
    baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
    gpgcheck: true
    gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: Install Plex Media Server package
  yum:
    name: plexmediaserver
    state: "{{ plex_version }}"

- name: Manage Plex user uid created by RPM
  user:
    name: plex
    uid: "{{ plex_user_uid }}"
  when: plex_user_uid is defined

- name: Start and enable plex
  service:
    name: plexmediaserver
    state: started
    enabled: true
