---
- name: Add plex repository
  yum_repository:
    name: plex
    description: Plex Media Server repo
    baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
    gpgcheck: true
    gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: Install Plex Media Server package
  yum:
    name: plexmediaserver
    state: "{{ plex_version }}"

- name: Manage Plex user create by RPM
  user:
    name: plex
    uid: "{{ plex_user_uid }}"
  when: plex_user_uid is defined

- name: Start and enable plex
  service:
    name: plexmediaserver
    state: started
    enabled: true

# todo: remove firewalld from this role
- name: Plex firewall rule
  firewalld:
    port: 32400/tcp
    permanent: true
    state: enabled
    immediate: true
