---
- name: Add plex repository key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ plex_repo_key_url }}"

- name: Add plex repository
  ansible.builtin.yum_repository:
    name: "{{ plex_repo_name }}"
    description: Plex Media Server repo
    baseurl: "{{ plex_repo_url }}"
    gpgcheck: true
    gpgkey: "{{ plex_repo_key_url }}"

- name: Install Plex Media Server package
  ansible.builtin.package:
    name: plexmediaserver
    state: "{{ plex_version }}"

- name: Manage Plex user uid created by RPM
  ansible.builtin.user:
    name: plex
    uid: "{{ plex_user_uid }}"
  when: plex_user_uid is defined

- name: Start and enable plex
  ansible.builtin.service:
    name: plexmediaserver
    state: started
    enabled: true
